/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.0.9 model.glb --transform
Author: AntijnvanderGun (https://sketchfab.com/AntijnvanderGun)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/stylized-ww1-plane-c4edeb0e410f46e8a4db320879f0a1db
Title: Stylized WW1 Plane
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/model-transformed.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]} scale={0.04}>
          <group name="365f4c91b47842d8b66a5eecbcbdb59dfbx" rotation={[Math.PI / 2, 0, 0]}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="polySurface172" position={[-0.83, 5.81, -1.09]} rotation={[0.01, 0.04, -0.06]}>
                  <group name="polySurface171" position={[0, -0.57, 14.21]} rotation={[0, 0, -2.64]}>
                    <group name="polySurface304" position={[0, -3.3, -12.84]}>
                      <mesh name="polySurface304_pasted__lambert2_0" geometry={nodes.polySurface304_pasted__lambert2_0.geometry} material={materials.pasted__lambert2} />
                    </group>
                    <group name="polySurface305" position={[0, -3.3, -12.84]}>
                      <mesh name="polySurface305_pasted__lambert2_0" geometry={nodes.polySurface305_pasted__lambert2_0.geometry} material={materials.pasted__lambert2} />
                    </group>
                    <group name="polySurface306" position={[0, -3.3, -12.84]}>
                      <mesh name="polySurface306_pasted__lambert2_0" geometry={nodes.polySurface306_pasted__lambert2_0.geometry} material={materials.pasted__lambert2} />
                    </group>
                    <group name="polySurface406" position={[0, 0.01, -0.61]}>
                      <mesh name="polySurface406_Tooner_0" geometry={nodes.polySurface406_Tooner_0.geometry} material={materials.Tooner} />
                    </group>
                  </group>
                  <group name="pCube1" position={[0, -0.57, 13.29]} rotation={[0, 0, 2.32]} scale={14.59}>
                    <mesh name="pCube1_Blur_effect_0" geometry={nodes.pCube1_Blur_effect_0.geometry} material={materials.Blur_effect} />
                  </group>
                  <group name="pCube4" position={[0, -0.57, 13.07]} rotation={[0, 0, 2.24]} scale={9.32}>
                    <mesh name="pCube4_Blur_effect_0" geometry={nodes.pCube4_Blur_effect_0.geometry} material={materials.Blur_effect} />
                  </group>
                  <group name="polySurface173" position={[-11.65, -1.36, 1.22]} rotation={[-0.07, 0, 0]}>
                    <group name="pCube7" position={[-1.08, -0.01, -2.1]}>
                      <mesh name="pCube7_lambert1_0" geometry={nodes.pCube7_lambert1_0.geometry} material={materials.lambert1} />
                    </group>
                    <group name="polySurface407" position={[11.65, -2.42, 0.38]} rotation={[-0.06, 0, 0]}>
                      <mesh name="polySurface407_Tooner_0" geometry={nodes.polySurface407_Tooner_0.geometry} material={materials.Tooner} />
                    </group>
                    <mesh name="polySurface173_pasted__lambert2_0" geometry={nodes.polySurface173_pasted__lambert2_0.geometry} material={materials.pasted__lambert2} />
                  </group>
                  <group name="polySurface174" position={[11.65, -1.4, 1.15]} rotation={[0.08, 0, 0]}>
                    <group name="pCube6" position={[1.37, 0.05, -2.02]} scale={[1, 1, 1.04]}>
                      <mesh name="pCube6_lambert1_0" geometry={nodes.pCube6_lambert1_0.geometry} material={materials.lambert1} />
                    </group>
                    <group name="polySurface408" position={[-11.65, -2.38, 0.46]} rotation={[-0.06, 0, 0]}>
                      <mesh name="polySurface408_Tooner_0" geometry={nodes.polySurface408_Tooner_0.geometry} material={materials.Tooner} />
                    </group>
                    <mesh name="polySurface174_pasted__lambert2_0" geometry={nodes.polySurface174_pasted__lambert2_0.geometry} material={materials.pasted__lambert2} />
                  </group>
                  <group name="polySurface182" position={[-0.02, 3.62, 4.33]} rotation={[-0.11, 0, 0]}>
                    <group name="polySurface165" position={[-12.34, 1.3, -3.48]} rotation={[3.13, 0, 0]} scale={-1}>
                      <group name="pCube8" position={[1.7, -0.02, -1.87]}>
                        <mesh name="pCube8_lambert1_0" geometry={nodes.pCube8_lambert1_0.geometry} material={materials.lambert1} />
                      </group>
                      <group name="polySurface410" position={[-12.36, -8.49, 0.83]} rotation={[3.08, 0, 0]} scale={-1}>
                        <mesh name="polySurface410_Tooner_0" geometry={nodes.polySurface410_Tooner_0.geometry} material={materials.Tooner} />
                      </group>
                      <mesh name="polySurface165_pasted__lambert2_0" geometry={nodes.polySurface165_pasted__lambert2_0.geometry} material={materials.pasted__lambert2} />
                    </group>
                    <group name="polySurface161" position={[12.39, 1.3, -3.44]} rotation={[0.17, 0, 0]}>
                      <group name="pCube5" position={[1.8, 0.08, -1.88]} scale={[1, 1, 0.87]}>
                        <mesh name="pCube5_lambert1_0" geometry={nodes.pCube5_lambert1_0.geometry} material={materials.lambert1} />
                      </group>
                      <group name="polySurface411" position={[-12.36, -8.49, 0.79]} rotation={[-0.06, 0, 0]}>
                        <mesh name="polySurface411_Tooner_0" geometry={nodes.polySurface411_Tooner_0.geometry} material={materials.Tooner} />
                      </group>
                      <mesh name="polySurface161_pasted__lambert2_0" geometry={nodes.polySurface161_pasted__lambert2_0.geometry} material={materials.pasted__lambert2} />
                    </group>
                    <group name="polySurface409" position={[0.02, -7.22, -3.17]}>
                      <mesh name="polySurface409_Tooner_0" geometry={nodes.polySurface409_Tooner_0.geometry} material={materials.Tooner} />
                    </group>
                    <mesh name="polySurface182_pasted__lambert2_0" geometry={nodes.polySurface182_pasted__lambert2_0.geometry} material={materials.pasted__lambert2} />
                  </group>
                  <group name="pCube10" position={[-6.25, 0.64, -12.78]}>
                    <mesh name="pCube10_lambert1_0" geometry={nodes.pCube10_lambert1_0.geometry} material={materials.lambert1} />
                  </group>
                  <group name="pCube9" position={[6.6, 0.66, -12.57]}>
                    <mesh name="pCube9_lambert1_0" geometry={nodes.pCube9_lambert1_0.geometry} material={materials.lambert1} />
                  </group>
                  <group name="pCube11" position={[0.03, 5.29, -12.12]}>
                    <mesh name="pCube11_lambert1_0" geometry={nodes.pCube11_lambert1_0.geometry} material={materials.lambert1} />
                  </group>
                  <group name="polySurface187" position={[0, -3.87, 1.37]}>
                    <mesh name="polySurface187_pasted__lambert2_0" geometry={nodes.polySurface187_pasted__lambert2_0.geometry} material={materials.pasted__lambert2} />
                  </group>
                  <group name="polySurface188" position={[0, -3.87, 1.37]}>
                    <mesh name="polySurface188_pasted__lambert2_0" geometry={nodes.polySurface188_pasted__lambert2_0.geometry} material={materials.pasted__lambert2} />
                  </group>
                  <group name="polySurface189" position={[0, -3.87, 1.37]}>
                    <mesh name="polySurface189_pasted__lambert2_0" geometry={nodes.polySurface189_pasted__lambert2_0.geometry} material={materials.pasted__lambert2} />
                  </group>
                  <group name="polySurface190" position={[0, -3.87, 1.37]}>
                    <mesh name="polySurface190_pasted__lambert2_0" geometry={nodes.polySurface190_pasted__lambert2_0.geometry} material={materials.pasted__lambert2} />
                  </group>
                  <group name="polySurface191" position={[0, -3.87, 1.37]}>
                    <mesh name="polySurface191_pasted__lambert2_0" geometry={nodes.polySurface191_pasted__lambert2_0.geometry} material={materials.pasted__lambert2} />
                  </group>
                  <group name="polySurface192" position={[0, -3.87, 1.37]}>
                    <mesh name="polySurface192_pasted__lambert2_0" geometry={nodes.polySurface192_pasted__lambert2_0.geometry} material={materials.pasted__lambert2} />
                  </group>
                  <group name="polySurface193" position={[0, -3.87, 1.37]}>
                    <mesh name="polySurface193_pasted__lambert2_0" geometry={nodes.polySurface193_pasted__lambert2_0.geometry} material={materials.pasted__lambert2} />
                  </group>
                  <group name="polySurface194" position={[0, -3.87, 1.37]}>
                    <mesh name="polySurface194_pasted__lambert2_0" geometry={nodes.polySurface194_pasted__lambert2_0.geometry} material={materials.pasted__lambert2} />
                  </group>
                  <group name="polySurface195" position={[0, -3.87, 1.37]}>
                    <mesh name="polySurface195_pasted__lambert2_0" geometry={nodes.polySurface195_pasted__lambert2_0.geometry} material={materials.pasted__lambert2} />
                  </group>
                  <group name="polySurface196" position={[0, -3.87, 1.37]}>
                    <mesh name="polySurface196_pasted__lambert2_0" geometry={nodes.polySurface196_pasted__lambert2_0.geometry} material={materials.pasted__lambert2} />
                  </group>
                  <group name="polySurface197" position={[0, -3.87, 1.37]}>
                    <mesh name="polySurface197_pasted__lambert2_0" geometry={nodes.polySurface197_pasted__lambert2_0.geometry} material={materials.pasted__lambert2} />
                  </group>
                  <group name="polySurface198" position={[0, -3.87, 1.37]}>
                    <mesh name="polySurface198_pasted__lambert2_0" geometry={nodes.polySurface198_pasted__lambert2_0.geometry} material={materials.pasted__lambert2} />
                  </group>
                  <group name="polySurface199" position={[0, -3.87, 1.37]}>
                    <mesh name="polySurface199_pasted__lambert2_0" geometry={nodes.polySurface199_pasted__lambert2_0.geometry} material={materials.pasted__lambert2} />
                  </group>
                  <group name="polySurface200" position={[0, -3.87, 1.37]}>
                    <mesh name="polySurface200_pasted__lambert2_0" geometry={nodes.polySurface200_pasted__lambert2_0.geometry} material={materials.pasted__lambert2} />
                  </group>
                  <group name="polySurface201" position={[0, -3.87, 1.37]}>
                    <mesh name="polySurface201_pasted__lambert2_0" geometry={nodes.polySurface201_pasted__lambert2_0.geometry} material={materials.pasted__lambert2} />
                  </group>
                  <group name="polySurface202" position={[0, -3.87, 1.37]}>
                    <mesh name="polySurface202_pasted__lambert2_0" geometry={nodes.polySurface202_pasted__lambert2_0.geometry} material={materials.pasted__lambert2} />
                  </group>
                  <group name="polySurface203" position={[0, -3.87, 1.37]}>
                    <mesh name="polySurface203_pasted__lambert2_0" geometry={nodes.polySurface203_pasted__lambert2_0.geometry} material={materials.pasted__lambert2} />
                  </group>
                  <group name="polySurface204" position={[0, -3.87, 1.37]}>
                    <mesh name="polySurface204_pasted__lambert2_0" geometry={nodes.polySurface204_pasted__lambert2_0.geometry} material={materials.pasted__lambert2} />
                  </group>
                  <group name="polySurface205" position={[0, -3.87, 1.37]}>
                    <mesh name="polySurface205_pasted__lambert2_0" geometry={nodes.polySurface205_pasted__lambert2_0.geometry} material={materials.pasted__lambert2} />
                  </group>
                  <group name="polySurface206" position={[0, -3.87, 1.37]}>
                    <mesh name="polySurface206_pasted__lambert2_0" geometry={nodes.polySurface206_pasted__lambert2_0.geometry} material={materials.pasted__lambert2} />
                  </group>
                  <group name="polySurface207" position={[0, -3.87, 1.37]}>
                    <mesh name="polySurface207_pasted__lambert2_0" geometry={nodes.polySurface207_pasted__lambert2_0.geometry} material={materials.pasted__lambert2} />
                  </group>
                  <group name="polySurface208" position={[0, -3.87, 1.37]}>
                    <mesh name="polySurface208_pasted__lambert2_0" geometry={nodes.polySurface208_pasted__lambert2_0.geometry} material={materials.pasted__lambert2} />
                  </group>
                  <group name="polySurface209" position={[0, -3.87, 1.37]}>
                    <mesh name="polySurface209_pasted__lambert2_0" geometry={nodes.polySurface209_pasted__lambert2_0.geometry} material={materials.pasted__lambert2} />
                  </group>
                  <group name="polySurface210" position={[0, -3.87, 1.37]}>
                    <mesh name="polySurface210_pasted__lambert2_0" geometry={nodes.polySurface210_pasted__lambert2_0.geometry} material={materials.pasted__lambert2} />
                  </group>
                  <group name="polySurface211" position={[0, -3.87, 1.37]}>
                    <mesh name="polySurface211_pasted__lambert2_0" geometry={nodes.polySurface211_pasted__lambert2_0.geometry} material={materials.pasted__lambert2} />
                  </group>
                  <group name="polySurface212" position={[0, -3.87, 1.37]}>
                    <mesh name="polySurface212_pasted__lambert2_0" geometry={nodes.polySurface212_pasted__lambert2_0.geometry} material={materials.pasted__lambert2} />
                  </group>
                  <group name="polySurface213" position={[0, -3.87, 1.37]}>
                    <mesh name="polySurface213_pasted__lambert2_0" geometry={nodes.polySurface213_pasted__lambert2_0.geometry} material={materials.pasted__lambert2} />
                  </group>
                  <group name="polySurface214" position={[0, -3.87, 1.37]}>
                    <mesh name="polySurface214_pasted__lambert2_0" geometry={nodes.polySurface214_pasted__lambert2_0.geometry} material={materials.pasted__lambert2} />
                  </group>
                  <group name="polySurface215" position={[0, -3.87, 1.37]}>
                    <mesh name="polySurface215_pasted__lambert2_0" geometry={nodes.polySurface215_pasted__lambert2_0.geometry} material={materials.pasted__lambert2} />
                  </group>
                  <group name="polySurface216" position={[0, -3.87, 1.37]}>
                    <mesh name="polySurface216_pasted__lambert2_0" geometry={nodes.polySurface216_pasted__lambert2_0.geometry} material={materials.pasted__lambert2} />
                  </group>
                  <group name="polySurface217" position={[0, -3.87, 1.37]}>
                    <mesh name="polySurface217_pasted__lambert2_0" geometry={nodes.polySurface217_pasted__lambert2_0.geometry} material={materials.pasted__lambert2} />
                  </group>
                  <group name="polySurface218" position={[0, -3.87, 1.37]}>
                    <mesh name="polySurface218_pasted__lambert2_0" geometry={nodes.polySurface218_pasted__lambert2_0.geometry} material={materials.pasted__lambert2} />
                  </group>
                  <group name="polySurface219" position={[0, -3.87, 1.37]}>
                    <mesh name="polySurface219_pasted__lambert2_0" geometry={nodes.polySurface219_pasted__lambert2_0.geometry} material={materials.pasted__lambert2} />
                  </group>
                  <group name="polySurface220" position={[0, -3.87, 1.37]}>
                    <mesh name="polySurface220_pasted__lambert2_0" geometry={nodes.polySurface220_pasted__lambert2_0.geometry} material={materials.pasted__lambert2} />
                  </group>
                  <group name="polySurface221" position={[0, -3.87, 1.37]}>
                    <mesh name="polySurface221_pasted__lambert2_0" geometry={nodes.polySurface221_pasted__lambert2_0.geometry} material={materials.pasted__lambert2} />
                  </group>
                  <group name="polySurface222" position={[0, -3.87, 1.37]}>
                    <mesh name="polySurface222_pasted__lambert2_0" geometry={nodes.polySurface222_pasted__lambert2_0.geometry} material={materials.pasted__lambert2} />
                  </group>
                  <group name="polySurface223" position={[0, -3.87, 1.37]}>
                    <mesh name="polySurface223_pasted__lambert2_0" geometry={nodes.polySurface223_pasted__lambert2_0.geometry} material={materials.pasted__lambert2} />
                  </group>
                  <group name="polySurface224" position={[0, -3.87, 1.37]}>
                    <mesh name="polySurface224_pasted__lambert2_0" geometry={nodes.polySurface224_pasted__lambert2_0.geometry} material={materials.pasted__lambert2} />
                  </group>
                  <group name="polySurface225" position={[0, -3.87, 1.37]}>
                    <mesh name="polySurface225_pasted__lambert2_0" geometry={nodes.polySurface225_pasted__lambert2_0.geometry} material={materials.pasted__lambert2} />
                  </group>
                  <group name="polySurface226" position={[0, -3.87, 1.37]}>
                    <mesh name="polySurface226_pasted__lambert2_0" geometry={nodes.polySurface226_pasted__lambert2_0.geometry} material={materials.pasted__lambert2} />
                  </group>
                  <group name="polySurface227" position={[0, -3.87, 1.37]}>
                    <mesh name="polySurface227_pasted__lambert2_0" geometry={nodes.polySurface227_pasted__lambert2_0.geometry} material={materials.pasted__lambert2} />
                  </group>
                  <group name="polySurface228" position={[0, -3.87, 1.37]}>
                    <mesh name="polySurface228_pasted__lambert2_0" geometry={nodes.polySurface228_pasted__lambert2_0.geometry} material={materials.pasted__lambert2} />
                  </group>
                  <group name="polySurface229" position={[0, -3.87, 1.37]}>
                    <mesh name="polySurface229_pasted__lambert2_0" geometry={nodes.polySurface229_pasted__lambert2_0.geometry} material={materials.pasted__lambert2} />
                  </group>
                  <group name="polySurface230" position={[0, -3.87, 1.37]}>
                    <mesh name="polySurface230_pasted__lambert2_0" geometry={nodes.polySurface230_pasted__lambert2_0.geometry} material={materials.pasted__lambert2} />
                  </group>
                  <group name="polySurface231" position={[0, -3.87, 1.37]}>
                    <mesh name="polySurface231_pasted__lambert2_0" geometry={nodes.polySurface231_pasted__lambert2_0.geometry} material={materials.pasted__lambert2} />
                  </group>
                  <group name="polySurface232" position={[0, -3.87, 1.37]}>
                    <mesh name="polySurface232_pasted__lambert2_0" geometry={nodes.polySurface232_pasted__lambert2_0.geometry} material={materials.pasted__lambert2} />
                  </group>
                  <group name="polySurface233" position={[0, -3.87, 1.37]}>
                    <mesh name="polySurface233_pasted__lambert2_0" geometry={nodes.polySurface233_pasted__lambert2_0.geometry} material={materials.pasted__lambert2} />
                  </group>
                  <group name="polySurface234" position={[0, -3.87, 1.37]}>
                    <mesh name="polySurface234_pasted__lambert2_0" geometry={nodes.polySurface234_pasted__lambert2_0.geometry} material={materials.pasted__lambert2} />
                  </group>
                  <group name="polySurface235" position={[0, -3.87, 1.37]}>
                    <mesh name="polySurface235_pasted__lambert2_0" geometry={nodes.polySurface235_pasted__lambert2_0.geometry} material={materials.pasted__lambert2} />
                  </group>
                  <group name="polySurface236" position={[0, -3.87, 1.37]}>
                    <mesh name="polySurface236_pasted__lambert2_0" geometry={nodes.polySurface236_pasted__lambert2_0.geometry} material={materials.pasted__lambert2} />
                  </group>
                  <group name="polySurface237" position={[0, -3.87, 1.37]}>
                    <mesh name="polySurface237_pasted__lambert2_0" geometry={nodes.polySurface237_pasted__lambert2_0.geometry} material={materials.pasted__lambert2} />
                  </group>
                  <group name="polySurface238" position={[0, -3.87, 1.37]}>
                    <mesh name="polySurface238_pasted__lambert2_0" geometry={nodes.polySurface238_pasted__lambert2_0.geometry} material={materials.pasted__lambert2} />
                  </group>
                  <group name="polySurface239" position={[0, -3.87, 1.37]}>
                    <mesh name="polySurface239_pasted__lambert2_0" geometry={nodes.polySurface239_pasted__lambert2_0.geometry} material={materials.pasted__lambert2} />
                  </group>
                  <group name="polySurface240" position={[0, -3.87, 1.37]}>
                    <mesh name="polySurface240_pasted__lambert2_0" geometry={nodes.polySurface240_pasted__lambert2_0.geometry} material={materials.pasted__lambert2} />
                  </group>
                  <group name="polySurface241" position={[0, -3.87, 1.37]}>
                    <mesh name="polySurface241_pasted__lambert2_0" geometry={nodes.polySurface241_pasted__lambert2_0.geometry} material={materials.pasted__lambert2} />
                  </group>
                  <group name="polySurface242" position={[0, -3.87, 1.37]}>
                    <mesh name="polySurface242_pasted__lambert2_0" geometry={nodes.polySurface242_pasted__lambert2_0.geometry} material={materials.pasted__lambert2} />
                  </group>
                  <group name="polySurface243" position={[0, -3.87, 1.37]}>
                    <mesh name="polySurface243_pasted__lambert2_0" geometry={nodes.polySurface243_pasted__lambert2_0.geometry} material={materials.pasted__lambert2} />
                  </group>
                  <group name="polySurface244" position={[0, -3.87, 1.37]}>
                    <mesh name="polySurface244_pasted__lambert2_0" geometry={nodes.polySurface244_pasted__lambert2_0.geometry} material={materials.pasted__lambert2} />
                  </group>
                  <group name="polySurface245" position={[0, -3.87, 1.37]}>
                    <mesh name="polySurface245_pasted__lambert2_0" geometry={nodes.polySurface245_pasted__lambert2_0.geometry} material={materials.pasted__lambert2} />
                  </group>
                  <group name="polySurface246" position={[0, -3.87, 1.37]}>
                    <mesh name="polySurface246_pasted__lambert2_0" geometry={nodes.polySurface246_pasted__lambert2_0.geometry} material={materials.pasted__lambert2} />
                  </group>
                  <group name="polySurface247" position={[0, -3.87, 1.37]}>
                    <mesh name="polySurface247_pasted__lambert2_0" geometry={nodes.polySurface247_pasted__lambert2_0.geometry} material={materials.pasted__lambert2} />
                  </group>
                  <group name="polySurface248" position={[0, -3.87, 1.37]}>
                    <mesh name="polySurface248_pasted__lambert2_0" geometry={nodes.polySurface248_pasted__lambert2_0.geometry} material={materials.pasted__lambert2} />
                  </group>
                  <group name="polySurface249" position={[0, -3.87, 1.37]}>
                    <mesh name="polySurface249_pasted__lambert2_0" geometry={nodes.polySurface249_pasted__lambert2_0.geometry} material={materials.pasted__lambert2} />
                  </group>
                  <group name="polySurface250" position={[0, -3.87, 1.37]}>
                    <mesh name="polySurface250_pasted__lambert2_0" geometry={nodes.polySurface250_pasted__lambert2_0.geometry} material={materials.pasted__lambert2} />
                  </group>
                  <group name="polySurface251" position={[0, -3.87, 1.37]}>
                    <mesh name="polySurface251_pasted__lambert2_0" geometry={nodes.polySurface251_pasted__lambert2_0.geometry} material={materials.pasted__lambert2} />
                  </group>
                  <group name="polySurface252" position={[0, -3.87, 1.37]}>
                    <mesh name="polySurface252_pasted__lambert2_0" geometry={nodes.polySurface252_pasted__lambert2_0.geometry} material={materials.pasted__lambert2} />
                  </group>
                  <group name="polySurface253" position={[0, -3.87, 1.37]}>
                    <mesh name="polySurface253_pasted__lambert2_0" geometry={nodes.polySurface253_pasted__lambert2_0.geometry} material={materials.pasted__lambert2} />
                  </group>
                  <group name="polySurface254" position={[0, -3.87, 1.37]}>
                    <mesh name="polySurface254_pasted__lambert2_0" geometry={nodes.polySurface254_pasted__lambert2_0.geometry} material={materials.pasted__lambert2} />
                  </group>
                  <group name="polySurface255" position={[0, -3.87, 1.37]}>
                    <mesh name="polySurface255_pasted__lambert2_0" geometry={nodes.polySurface255_pasted__lambert2_0.geometry} material={materials.pasted__lambert2} />
                  </group>
                  <group name="polySurface256" position={[0, -3.87, 1.37]}>
                    <mesh name="polySurface256_pasted__lambert2_0" geometry={nodes.polySurface256_pasted__lambert2_0.geometry} material={materials.pasted__lambert2} />
                  </group>
                  <group name="polySurface257" position={[0, -3.87, 1.37]}>
                    <mesh name="polySurface257_pasted__lambert2_0" geometry={nodes.polySurface257_pasted__lambert2_0.geometry} material={materials.pasted__lambert2} />
                  </group>
                  <group name="polySurface258" position={[0, -3.87, 1.37]}>
                    <mesh name="polySurface258_pasted__lambert2_0" geometry={nodes.polySurface258_pasted__lambert2_0.geometry} material={materials.pasted__lambert2} />
                  </group>
                  <group name="polySurface259" position={[0, -3.87, 1.37]}>
                    <mesh name="polySurface259_pasted__lambert2_0" geometry={nodes.polySurface259_pasted__lambert2_0.geometry} material={materials.pasted__lambert2} />
                  </group>
                  <group name="polySurface260" position={[0, -3.87, 1.37]}>
                    <mesh name="polySurface260_pasted__lambert2_0" geometry={nodes.polySurface260_pasted__lambert2_0.geometry} material={materials.pasted__lambert2} />
                  </group>
                  <group name="polySurface261" position={[0, -3.87, 1.37]}>
                    <mesh name="polySurface261_pasted__lambert2_0" geometry={nodes.polySurface261_pasted__lambert2_0.geometry} material={materials.pasted__lambert2} />
                  </group>
                  <group name="polySurface262" position={[0, -3.87, 1.37]}>
                    <mesh name="polySurface262_pasted__lambert2_0" geometry={nodes.polySurface262_pasted__lambert2_0.geometry} material={materials.pasted__lambert2} />
                  </group>
                  <group name="polySurface263" position={[0, -3.87, 1.37]}>
                    <mesh name="polySurface263_pasted__lambert2_0" geometry={nodes.polySurface263_pasted__lambert2_0.geometry} material={materials.pasted__lambert2} />
                  </group>
                  <group name="polySurface264" position={[0, -3.87, 1.37]}>
                    <mesh name="polySurface264_pasted__lambert2_0" geometry={nodes.polySurface264_pasted__lambert2_0.geometry} material={materials.pasted__lambert2} />
                  </group>
                  <group name="polySurface265" position={[0, -3.87, 1.37]}>
                    <mesh name="polySurface265_pasted__lambert2_0" geometry={nodes.polySurface265_pasted__lambert2_0.geometry} material={materials.pasted__lambert2} />
                  </group>
                  <group name="polySurface266" position={[0, -3.87, 1.37]}>
                    <mesh name="polySurface266_pasted__lambert2_0" geometry={nodes.polySurface266_pasted__lambert2_0.geometry} material={materials.pasted__lambert2} />
                  </group>
                  <group name="polySurface267" position={[0, -3.87, 1.37]}>
                    <mesh name="polySurface267_pasted__lambert2_0" geometry={nodes.polySurface267_pasted__lambert2_0.geometry} material={materials.pasted__lambert2} />
                  </group>
                  <group name="polySurface268" position={[0, -3.87, 1.37]}>
                    <mesh name="polySurface268_pasted__lambert2_0" geometry={nodes.polySurface268_pasted__lambert2_0.geometry} material={materials.pasted__lambert2} />
                  </group>
                  <group name="polySurface269" position={[0, -3.87, 1.37]}>
                    <mesh name="polySurface269_pasted__lambert2_0" geometry={nodes.polySurface269_pasted__lambert2_0.geometry} material={materials.pasted__lambert2} />
                  </group>
                  <group name="polySurface270" position={[0, -3.87, 1.37]}>
                    <mesh name="polySurface270_pasted__lambert2_0" geometry={nodes.polySurface270_pasted__lambert2_0.geometry} material={materials.pasted__lambert2} />
                  </group>
                  <group name="polySurface271" position={[0, -3.87, 1.37]}>
                    <mesh name="polySurface271_pasted__lambert2_0" geometry={nodes.polySurface271_pasted__lambert2_0.geometry} material={materials.pasted__lambert2} />
                  </group>
                  <group name="polySurface272" position={[0, -3.87, 1.37]}>
                    <mesh name="polySurface272_pasted__lambert2_0" geometry={nodes.polySurface272_pasted__lambert2_0.geometry} material={materials.pasted__lambert2} />
                  </group>
                  <group name="polySurface273" position={[0, -3.87, 1.37]}>
                    <mesh name="polySurface273_pasted__lambert2_0" geometry={nodes.polySurface273_pasted__lambert2_0.geometry} material={materials.pasted__lambert2} />
                  </group>
                  <group name="polySurface274" position={[0, -3.87, 1.37]}>
                    <mesh name="polySurface274_pasted__lambert2_0" geometry={nodes.polySurface274_pasted__lambert2_0.geometry} material={materials.pasted__lambert2} />
                  </group>
                  <group name="polySurface275" position={[0, -3.87, 1.37]}>
                    <mesh name="polySurface275_pasted__lambert2_0" geometry={nodes.polySurface275_pasted__lambert2_0.geometry} material={materials.pasted__lambert2} />
                  </group>
                  <group name="polySurface276" position={[0, -3.87, 1.37]}>
                    <mesh name="polySurface276_pasted__lambert2_0" geometry={nodes.polySurface276_pasted__lambert2_0.geometry} material={materials.pasted__lambert2} />
                  </group>
                  <group name="polySurface277" position={[0, -3.87, 1.37]}>
                    <mesh name="polySurface277_pasted__lambert2_0" geometry={nodes.polySurface277_pasted__lambert2_0.geometry} material={materials.pasted__lambert2} />
                  </group>
                  <group name="polySurface278" position={[0, -3.87, 1.37]}>
                    <mesh name="polySurface278_pasted__lambert2_0" geometry={nodes.polySurface278_pasted__lambert2_0.geometry} material={materials.pasted__lambert2} />
                  </group>
                  <group name="polySurface279" position={[0, -3.87, 1.37]}>
                    <mesh name="polySurface279_pasted__lambert2_0" geometry={nodes.polySurface279_pasted__lambert2_0.geometry} material={materials.pasted__lambert2} />
                  </group>
                  <group name="polySurface280" position={[0, -3.87, 1.37]}>
                    <mesh name="polySurface280_pasted__lambert2_0" geometry={nodes.polySurface280_pasted__lambert2_0.geometry} material={materials.pasted__lambert2} />
                  </group>
                  <group name="polySurface281" position={[0, -3.87, 1.37]}>
                    <mesh name="polySurface281_pasted__lambert2_0" geometry={nodes.polySurface281_pasted__lambert2_0.geometry} material={materials.pasted__lambert2} />
                  </group>
                  <group name="polySurface282" position={[0, -3.87, 1.37]}>
                    <mesh name="polySurface282_pasted__lambert2_0" geometry={nodes.polySurface282_pasted__lambert2_0.geometry} material={materials.pasted__lambert2} />
                  </group>
                  <group name="polySurface283" position={[0, -3.87, 1.37]}>
                    <mesh name="polySurface283_pasted__lambert2_0" geometry={nodes.polySurface283_pasted__lambert2_0.geometry} material={materials.pasted__lambert2} />
                  </group>
                  <group name="polySurface284" position={[0, -3.87, 1.37]}>
                    <mesh name="polySurface284_pasted__lambert2_0" geometry={nodes.polySurface284_pasted__lambert2_0.geometry} material={materials.pasted__lambert2} />
                  </group>
                  <group name="polySurface285" position={[0, -3.87, 1.37]}>
                    <mesh name="polySurface285_pasted__lambert2_0" geometry={nodes.polySurface285_pasted__lambert2_0.geometry} material={materials.pasted__lambert2} />
                  </group>
                  <group name="polySurface286" position={[0, -3.87, 1.37]}>
                    <mesh name="polySurface286_pasted__lambert2_0" geometry={nodes.polySurface286_pasted__lambert2_0.geometry} material={materials.pasted__lambert2} />
                  </group>
                  <group name="polySurface287" position={[0, -3.87, 1.37]}>
                    <mesh name="polySurface287_pasted__lambert2_0" geometry={nodes.polySurface287_pasted__lambert2_0.geometry} material={materials.pasted__lambert2} />
                  </group>
                  <group name="polySurface288" position={[0, -3.87, 1.37]}>
                    <mesh name="polySurface288_pasted__lambert2_0" geometry={nodes.polySurface288_pasted__lambert2_0.geometry} material={materials.pasted__lambert2} />
                  </group>
                  <group name="polySurface289" position={[0, -3.87, 1.37]}>
                    <mesh name="polySurface289_pasted__lambert2_0" geometry={nodes.polySurface289_pasted__lambert2_0.geometry} material={materials.pasted__lambert2} />
                  </group>
                  <group name="polySurface290" position={[0, -3.87, 1.37]}>
                    <mesh name="polySurface290_pasted__lambert2_0" geometry={nodes.polySurface290_pasted__lambert2_0.geometry} material={materials.pasted__lambert2} />
                  </group>
                  <group name="polySurface291" position={[0, -3.87, 1.37]}>
                    <mesh name="polySurface291_pasted__lambert2_0" geometry={nodes.polySurface291_pasted__lambert2_0.geometry} material={materials.pasted__lambert2} />
                  </group>
                  <group name="polySurface292" position={[0, -3.87, 1.37]}>
                    <mesh name="polySurface292_pasted__lambert2_0" geometry={nodes.polySurface292_pasted__lambert2_0.geometry} material={materials.pasted__lambert2} />
                  </group>
                  <group name="polySurface293" position={[0, -3.87, 1.37]}>
                    <mesh name="polySurface293_pasted__lambert2_0" geometry={nodes.polySurface293_pasted__lambert2_0.geometry} material={materials.pasted__lambert2} />
                  </group>
                  <group name="polySurface294" position={[0, -3.87, 1.37]}>
                    <mesh name="polySurface294_pasted__lambert2_0" geometry={nodes.polySurface294_pasted__lambert2_0.geometry} material={materials.pasted__lambert2} />
                  </group>
                  <group name="polySurface295" position={[0, -3.87, 1.37]}>
                    <mesh name="polySurface295_pasted__lambert2_0" geometry={nodes.polySurface295_pasted__lambert2_0.geometry} material={materials.pasted__lambert2} />
                  </group>
                  <group name="polySurface296" position={[0, -3.87, 1.37]}>
                    <mesh name="polySurface296_pasted__lambert2_0" geometry={nodes.polySurface296_pasted__lambert2_0.geometry} material={materials.pasted__lambert2} />
                  </group>
                  <group name="polySurface297" position={[0, -3.87, 1.37]}>
                    <mesh name="polySurface297_pasted__lambert2_0" geometry={nodes.polySurface297_pasted__lambert2_0.geometry} material={materials.pasted__lambert2} />
                  </group>
                  <group name="polySurface298" position={[0, -3.87, 1.37]}>
                    <mesh name="polySurface298_pasted__lambert2_0" geometry={nodes.polySurface298_pasted__lambert2_0.geometry} material={materials.pasted__lambert2} />
                  </group>
                  <group name="polySurface299" position={[0, -3.87, 1.37]}>
                    <mesh name="polySurface299_pasted__lambert2_0" geometry={nodes.polySurface299_pasted__lambert2_0.geometry} material={materials.pasted__lambert2} />
                  </group>
                  <group name="polySurface300" position={[0, -3.87, 1.37]}>
                    <mesh name="polySurface300_pasted__lambert2_0" geometry={nodes.polySurface300_pasted__lambert2_0.geometry} material={materials.pasted__lambert2} />
                  </group>
                  <group name="polySurface301" position={[0, -3.87, 1.37]}>
                    <mesh name="polySurface301_pasted__lambert2_0" geometry={nodes.polySurface301_pasted__lambert2_0.geometry} material={materials.pasted__lambert2} />
                  </group>
                  <group name="polySurface302" position={[0, -3.87, 1.37]}>
                    <mesh name="polySurface302_pasted__lambert2_0" geometry={nodes.polySurface302_pasted__lambert2_0.geometry} material={materials.pasted__lambert2} />
                  </group>
                  <group name="polySurface303" position={[0, -3.87, 1.37]}>
                    <mesh name="polySurface303_pasted__lambert2_0" geometry={nodes.polySurface303_pasted__lambert2_0.geometry} material={materials.pasted__lambert2} />
                  </group>
                  <group name="polySurface308" position={[0, 0.09, 0.04]}>
                    <mesh name="polySurface308_Tooner_0" geometry={nodes.polySurface308_Tooner_0.geometry} material={materials.Tooner} />
                  </group>
                </group>
                <group name="nurbsCircle1" position={[0, 0, -4.2]}>
                  <group name="pCube12" position={[27.47, 9.74, -42.13]} scale={0}>
                    <mesh name="pCube12_lambert1_0" geometry={nodes.pCube12_lambert1_0.geometry} material={materials.lambert1} />
                  </group>
                </group>
                <group name="nurbsCircle2" position={[-8.75, -5.27, 10.96]}>
                  <group name="pCube12_1" position={[27.47, 9.74, -41.48]} scale={0.01}>
                    <mesh name="pCube12_lambert1_0_1" geometry={nodes.pCube12_lambert1_0_1.geometry} material={materials.lambert1} />
                  </group>
                </group>
                <group name="nurbsCircle3" position={[-7.43, 8.26, -16.66]}>
                  <group name="pCube12_9" position={[27.47, 9.74, 25.69]} scale={0}>
                    <mesh name="pCube12_lambert1_0_9" geometry={nodes.pCube12_lambert1_0_9.geometry} material={materials.lambert1} />
                  </group>
                </group>
                <group name="nurbsCircle4" position={[-19.1, 5.53, -0.44]}>
                  <group name="pCube12_2" position={[27.47, 9.74, 41.91]} scale={0}>
                    <mesh name="pCube12_lambert1_0_2" geometry={nodes.pCube12_lambert1_0_2.geometry} material={materials.lambert1} />
                  </group>
                </group>
                <group name="nurbsCircle5" position={[-14.62, -16.61, -6.16]}>
                  <group name="pCube12_3" position={[27.47, 9.74, 36.19]} scale={0}>
                    <mesh name="pCube12_lambert1_0_3" geometry={nodes.pCube12_lambert1_0_3.geometry} material={materials.lambert1} />
                  </group>
                </group>
                <group name="nurbsCircle6" position={[-24.31, -17.68, 1.91]}>
                  <group name="pCube12_4" position={[27.47, 9.74, 11.38]} scale={0.89}>
                    <mesh name="pCube12_lambert1_0_4" geometry={nodes.pCube12_lambert1_0_4.geometry} material={materials.lambert1} />
                  </group>
                </group>
                <group name="nurbsCircle7" position={[-27.88, 7.69, 7.91]}>
                  <group name="pCube12_10" position={[27.47, 9.74, 50.26]} scale={0}>
                    <mesh name="pCube12_lambert1_0_10" geometry={nodes.pCube12_lambert1_0_10.geometry} material={materials.lambert1} />
                  </group>
                </group>
                <group name="nurbsCircle8" position={[-40.06, 10.44, -13.22]}>
                  <group name="pCube12_5" position={[27.47, 9.74, -10.46]} scale={0}>
                    <mesh name="pCube12_lambert1_0_5" geometry={nodes.pCube12_lambert1_0_5.geometry} material={materials.lambert1} />
                  </group>
                </group>
                <group name="nurbsCircle9" position={[-48.15, 2.47, 2.45]}>
                  <group name="pCube12_6" position={[27.47, 9.74, 36.19]} scale={0}>
                    <mesh name="pCube12_lambert1_0_6" geometry={nodes.pCube12_lambert1_0_6.geometry} material={materials.lambert1} />
                  </group>
                </group>
                <group name="nurbsCircle10" position={[-38.16, -10.89, -6.16]}>
                  <group name="pCube12_7" position={[27.47, 9.74, 36.19]} scale={0}>
                    <mesh name="pCube12_lambert1_0_7" geometry={nodes.pCube12_lambert1_0_7.geometry} material={materials.lambert1} />
                  </group>
                </group>
                <group name="nurbsCircle11" position={[-46.04, -5.98, -16.95]}>
                  <group name="pCube12_8" position={[27.47, 9.74, -22.82]} scale={0.37}>
                    <mesh name="pCube12_lambert1_0_8" geometry={nodes.pCube12_lambert1_0_8.geometry} material={materials.lambert1} />
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/model-transformed.glb')
