/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.0.9 plant.glb
Author: Giora (https://sketchfab.com/ChubbyPanda)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/monstera-deliciosa-potted-mid-century-plant-1ab9bf841df04c07b1819be596327629
Title: Monstera Deliciosa Potted Mid-Century plant
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function ModelPlant(props) {
  const { nodes, materials } = useGLTF('/plant.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.86}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <mesh geometry={nodes.root_HP_1_Mat2_0.geometry} material={materials['Mat.2']} position={[0.07, 0.06, 0.22]} />
          <mesh geometry={nodes.Stand_Mat_0.geometry} material={materials.material} position={[0, 2.45, 7.59]} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/plant.glb')
